/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

import javax.swing.JList;

/**
 *
 * @author jessica.sobreviela
 */
public class VistaParecidos extends javax.swing.JFrame {

    private static String autor;
    private static String titulo;
    private static Integer k;
    private static String type;
    private static boolean tfidf;
    private static boolean frec;
    private static JList lista;

    /**
     * Creates new form VistaParecidos
     * @param autor
     * @param titulo
     */
    public VistaParecidos(String autor, String titulo) {
        initComponents();
        VistaParecidos.autor = autor;
        VistaParecidos.titulo = titulo;
        VistaParecidos.tfidf = false;
        VistaParecidos.frec = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        textoNumDocs = new javax.swing.JLabel();
        textoResult = new javax.swing.JLabel();
        Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneNumDocs = new javax.swing.JTextPane();
        Aceptar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaResult = new javax.swing.JTextArea();
        textoBusqueda = new javax.swing.JLabel();
        FREC = new javax.swing.JRadioButton();
        TFIDF = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"k\" documentos más parecidos");
        getContentPane().setLayout(null);

        textoNumDocs.setText("Número de documentos:");
        getContentPane().add(textoNumDocs);
        textoNumDocs.setBounds(50, 61, 173, 17);

        textoResult.setText("Resultado:");
        getContentPane().add(textoResult);
        textoResult.setBounds(68, 207, 73, 17);

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(Consultar);
        Consultar.setBounds(321, 170, 82, 31);

        jScrollPane1.setViewportView(textPaneNumDocs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 60, 80, 26);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar);
        Aceptar.setBounds(334, 333, 69, 31);

        textAreaResult.setEditable(false);
        textAreaResult.setColumns(20);
        textAreaResult.setRows(5);
        jScrollPane3.setViewportView(textAreaResult);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(141, 228, 262, 87);

        textoBusqueda.setText("Método de búsqueda :");
        getContentPane().add(textoBusqueda);
        textoBusqueda.setBounds(50, 103, 155, 17);

        FREC.setText("Frecuencias");
        FREC.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                FRECComponentAdded(evt);
            }
        });
        FREC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRECActionPerformed(evt);
            }
        });
        getContentPane().add(FREC);
        FREC.setBounds(217, 100, 110, 23);

        TFIDF.setText("Tf-Idf");
        TFIDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIDFActionPerformed(evt);
            }
        });
        getContentPane().add(TFIDF);
        TFIDF.setBounds(217, 129, 65, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        if (VistaParecidos.tfidf) VistaParecidos.type = "TF-IDF";
        else VistaParecidos.type = "FREC";
        
        
    }//GEN-LAST:event_ConsultarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_AceptarActionPerformed

    private void TFIDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIDFActionPerformed
        // TODO add your handling code here:
        VistaParecidos.tfidf = true;
        VistaParecidos.frec = false;
    }//GEN-LAST:event_TFIDFActionPerformed

    private void FRECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRECActionPerformed
        // TODO add your handling code here:
        VistaParecidos.tfidf = false;
        VistaParecidos.frec = true;
    }//GEN-LAST:event_FRECActionPerformed

    private void FRECComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_FRECComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_FRECComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaParecidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaParecidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaParecidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaParecidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaParecidos(autor,titulo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Consultar;
    private javax.swing.JRadioButton FREC;
    private javax.swing.JRadioButton TFIDF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textAreaResult;
    private javax.swing.JTextPane textPaneNumDocs;
    private javax.swing.JLabel textoBusqueda;
    private javax.swing.JLabel textoNumDocs;
    private javax.swing.JLabel textoResult;
    // End of variables declaration//GEN-END:variables
}
