/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jessica.sobreviela
 */
public class VistaModificarAutor extends javax.swing.JFrame {
    private static String a;
    private static String t;
    private static CtrlPresentacio cp;
    private String nuevo_autor;
    /**
     * Creates new form VistaModificarAutor
     * @param cp
     * @param autor
     * @param titulo
     */
    public VistaModificarAutor(CtrlPresentacio cp, String autor, String titulo) {
        VistaModificarAutor.a=autor;
        VistaModificarAutor.t=titulo;
        VistaModificarAutor.cp = cp;
        textFieldAutor.setText(autor);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autor = new javax.swing.JLabel();
        nuevoAutor = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        textFieldAutor = new javax.swing.JTextField();
        textFieldNuevoAutor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 350));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        autor.setText("Autor:");
        getContentPane().add(autor);
        autor.setBounds(70, 60, 43, 17);

        nuevoAutor.setText("Nuevo autor:");
        getContentPane().add(nuevoAutor);
        nuevoAutor.setBounds(30, 130, 90, 17);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(386, 300, 90, 31);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(290, 300, 90, 31);

        textFieldAutor.setEditable(false);
        getContentPane().add(textFieldAutor);
        textFieldAutor.setBounds(150, 60, 300, 29);

        textFieldNuevoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNuevoAutorActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldNuevoAutor);
        textFieldNuevoAutor.setBounds(150, 130, 300, 29);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        textFieldNuevoAutorActionPerformed(evt);
        if (nuevo_autor != null && !nuevo_autor.isEmpty()) try {
            cp.modificarAutor(a,t,nuevo_autor);
            this.setVisible(false);
        } catch (IOException ex) {
            String excepcion = "Escriba un autor.";
            JOptionPane.showMessageDialog(rootPane,excepcion);
            Logger.getLogger(VistaModificarAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void textFieldNuevoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNuevoAutorActionPerformed
        this.nuevo_autor = textFieldNuevoAutor.getText();
    }//GEN-LAST:event_textFieldNuevoAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarAutor(cp, a, t).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel autor;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nuevoAutor;
    private javax.swing.JTextField textFieldAutor;
    private javax.swing.JTextField textFieldNuevoAutor;
    // End of variables declaration//GEN-END:variables
}
