/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

/**
 *
 * @author jessica.sobreviela
 */
public class VistaConsultas extends javax.swing.JPanel {
    private static String autor;
    private static String titulo;
    private static String contenido;
    
    /**
     * Creates new form VistaConsultas
     * @param autor
     * @param titulo
     * @param contenido
     */
    public VistaConsultas(String autor, String titulo, String contenido) {
        initComponents();
        VistaConsultas.autor=autor;
        VistaConsultas.titulo=titulo;
        VistaConsultas.contenido=contenido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaContenido = new javax.swing.JButton();
        ConsultaParecidos = new javax.swing.JButton();
        ConsultaExpBooleana = new javax.swing.JButton();

        ConsultaContenido.setText("Consultar contenido");
        ConsultaContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaContenidoActionPerformed(evt);
            }
        });

        ConsultaParecidos.setText("Consultar Parecidos");
        ConsultaParecidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaParecidosActionPerformed(evt);
            }
        });

        ConsultaExpBooleana.setText("Consultar Expresión booleana");
        ConsultaExpBooleana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaExpBooleanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConsultaParecidos)
                            .addComponent(ConsultaContenido))
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ConsultaExpBooleana)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(ConsultaContenido)
                .addGap(18, 18, 18)
                .addComponent(ConsultaParecidos)
                .addGap(18, 18, 18)
                .addComponent(ConsultaExpBooleana)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaContenidoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ConsultaContenidoActionPerformed

    private void ConsultaParecidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaParecidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaParecidosActionPerformed

    private void ConsultaExpBooleanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaExpBooleanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaExpBooleanaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaContenido;
    private javax.swing.JButton ConsultaExpBooleana;
    private javax.swing.JButton ConsultaParecidos;
    // End of variables declaration//GEN-END:variables
}
