/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacio;

import java.util.ArrayList;
import jdk.nashorn.internal.codegen.CompilerConstants;

/**
 *
 * @author florencia.rimolo
 */
public class VistaAnadirDocumento extends javax.swing.JFrame {
    private String autor;
    private String titulo;
    private String contenido;
    private boolean botonAceptarApretado;
    private boolean botonCancelarApretado;
    private ArrayList<String> doc;
    /**
     * Creates new form VistaAnadirDocumento
     */
    public VistaAnadirDocumento() {
        initComponents();
        this.doc = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAutor = new java.awt.Label();
        labelTitulo = new java.awt.Label();
        labelContenido = new java.awt.Label();
        textFieldAutor = new javax.swing.JTextField();
        textFieldTitulo = new javax.swing.JTextField();
        textFieldContenido = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir documento");
        setPreferredSize(new java.awt.Dimension(1070, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        labelAutor.setBackground(new java.awt.Color(11, 116, 163));
        labelAutor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelAutor.setForeground(new java.awt.Color(255, 255, 255));
        labelAutor.setText("Autor:");
        getContentPane().add(labelAutor);
        labelAutor.setBounds(60, 80, 60, 30);

        labelTitulo.setBackground(new java.awt.Color(11, 116, 163));
        labelTitulo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Título:");
        getContentPane().add(labelTitulo);
        labelTitulo.setBounds(60, 150, 49, 29);

        labelContenido.setBackground(new java.awt.Color(11, 116, 163));
        labelContenido.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelContenido.setForeground(new java.awt.Color(255, 255, 255));
        labelContenido.setText("Contenido:");
        getContentPane().add(labelContenido);
        labelContenido.setBounds(50, 210, 82, 22);
        labelContenido.getAccessibleContext().setAccessibleName("");

        textFieldAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAutorActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldAutor);
        textFieldAutor.setBounds(150, 80, 310, 29);

        textFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTituloActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldTitulo);
        textFieldTitulo.setBounds(150, 150, 310, 29);

        textFieldContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldContenidoActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldContenido);
        textFieldContenido.setBounds(150, 210, 895, 290);

        botonAceptar.setBackground(new java.awt.Color(174, 178, 194));
        botonAceptar.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        botonAceptar.setText("Aceptar");
        botonAceptar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 178, 194), 1, true));
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar);
        botonAceptar.setBounds(840, 550, 90, 30);

        botonCancelar.setBackground(new java.awt.Color(174, 178, 194));
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(174, 178, 194), 1, true));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar);
        botonCancelar.setBounds(960, 550, 90, 30);

        fondo.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("url:http://www.celer-comex.com.ar/images/fondo.jpg")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        fondo.setToolTipText("");
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1100, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTituloActionPerformed
        // TODO add your handling code here:
        this.titulo = textFieldTitulo.getText();
        botonAceptarApretado = false;
        botonCancelarApretado = false;
    }//GEN-LAST:event_textFieldTituloActionPerformed

    private void textFieldContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldContenidoActionPerformed
        // TODO add your handling code here:
        this.contenido = textFieldContenido.getText();
        botonAceptarApretado = false;
    }//GEN-LAST:event_textFieldContenidoActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        botonAceptarApretado = false;
        botonCancelarApretado = true;
        this.setVisible(false);
        //System.exit(0);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        textFieldAutorActionPerformed(evt);
        textFieldContenidoActionPerformed(evt);
        textFieldTituloActionPerformed(evt);
        doc.add(this.autor);
        doc.add(this.titulo);
        doc.add(this.contenido);
        botonAceptarApretado = true;
        this.setVisible(false);
        for (String s: doc) {
            System.out.println(s);
        }
        System.out.println(this.autor);
        System.out.println(this.titulo);
        System.out.println(this.contenido);
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textFieldAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAutorActionPerformed
        // TODO add your handling code here:
        botonAceptarApretado = false;
        botonCancelarApretado = false;
        this.autor = textFieldAutor.getText();
    }//GEN-LAST:event_textFieldAutorActionPerformed

    public ArrayList<String> getDocumento() {
        return this.doc;
    }
    public boolean botonAceptarApretado() {
        return this.botonAceptarApretado;
    }
    
    public boolean botonCancelarApretado() {
        return this.botonCancelarApretado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAnadirDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAnadirDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAnadirDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAnadirDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAnadirDocumento().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel fondo;
    private java.awt.Label labelAutor;
    private java.awt.Label labelContenido;
    private java.awt.Label labelTitulo;
    private javax.swing.JTextField textFieldAutor;
    private javax.swing.JTextField textFieldContenido;
    private javax.swing.JTextField textFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
